### ISSUE TITLE
Improve get-started page

### ISSUE THREAD

**Issue by fu31** [0xhokusai/hokusai-api-docs#53]
## Description
Improve get-started page

## Objectives
Make the page more development-friendly.

## Proposals
Fix sentences section
Write detailed information about nft.storage, get-nft, mint-nft 

## Tasks
- [ ] fix sentence section
- [ ] Write detailed information about nft.storage, 
- [ ] Write detailed information about get-nft
- [ ] Write detailed information about mint-nft
